[package]
name = "im_installer"
version = "0.1.0"
edition = "2024"

[dependencies]
vizia = { git = "https://github.com/vizia/vizia" }
rfd = "0.16.0"

[target.'cfg(windows)'.dependencies]
windows-elevate = "0.1.0"
privesc = "1.2.0"
